# -*- coding: utf-8 -*-
"""comparesigning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KPY5L2PnXCPiM31wWIxq6Vjgx0MT2k12
"""

#@title
import csv
from google.colab import files
import datetime
from datetime import datetime
import io

def UploadFile():
    """Upload a file and return its content as an io string."""
    for fn in uploaded.keys():
        content_str = uploaded[fn].decode("utf-8")
        return io.StringIO(content_str)

def check(str1, str2, format_str):
    """Check if two strings are equal (based on format), or both are redacted."""
    try:
        str1_conv = datetime.strptime(str1, format_str)
        str2_conv = datetime.strptime(str2, format_str)
        if str1_conv == str2_conv:
            return True
        else:
            return False
    except ValueError:
        if str1 == str2:
            return True  # both are redacted the same way, assume correct.
        else:
            return False 


def redactionated(date1, date2):
    if date1 != "(None entered)" and date2 != "(None Entered)":
        dated1 = date1.split("/")
        dated2 = date2.split("/")
        month_ok = check(dated1[0], dated2[0], '%m')
        day_ok = check(dated1[1], dated2[1], '%d')
        year_ok = check(dated1[2], dated2[2], '%Y')
        if (month_ok and day_ok and year_ok):
            return("OK")
        else:
            return("spain", date1, "and", date2)

def comparesigning(date1, date2):
    try:
        dated1 = datetime.strptime(date1, '%d/%m/%Y')
        dated2 = datetime.strptime(date2, '%d/%m/%Y')
        if dated1 == dated2:
            return("OK")
        else:
            return("spain", date1, "and", date2)
    except ValueError:
        return redactionated(date1, date2)

uploaded = files.upload()

#@title
def UploadAndProcessFile():
    reader = csv.DictReader(UploadFile(), delimiter='\t')
    count = 1
    fout = open("lister.txt", "w")
    #========
    for row in reader:
        count += 1
        print(count, comparesigning(row["agreement"], row["effective"]))
    fout.close()

UploadAndProcessFile()

#@title
count = 1
def butwhatif(str1, str2):
    if str1 == "(None entered)" or str2 == "(None entered)":
        return("")
    if str1.strip() == str2.strip():
        return("")
    else:
        return(count, str1, str2)

#@title
reader = csv.DictReader(UploadFile(), delimiter='\t')
count = 1
#========
for row in reader:
    count += 1
    str1 = row["Agreement Date-Answer (mm/dd/year)"]
    str2 = row["Effective Date-Answer (mm/dd/year)"]
    
    if str1 == "(None entered)" or str2 == "(None entered)":
        placer = 1
    else:
        if str1.strip() == str2.strip():
            placer = 1
        else:
            print(count, str1, str2)